# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Test Bot Code Validity

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install PyYAML 5.3.1
      run: |
        sudo apt-get install autoconf libtool make
        git clone https://github.com/yaml/libyaml
        cd libyaml
        ./bootstrap
        ./configure
        sudo make
        sudo make install
        cd ..
        7z x PyYAML-5.3.1.tar.gz -y -o.
        7z x dist/PyYAML-5.3.1.tar -y -o.
        cd PyYAML-5.3.1
        python setup.py --with-libyaml install
        cd ..
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./src --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
